version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: know_your_fan
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: know_your_fan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL_LOCAL: postgresql://know_your_fan:123456@db:5432/know_your_fan
    restart: always

volumes:
  postgres_data:
